name: Set up Python

on: workflow_call

jobs:
  python-setup:
    name: Set up Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print Python version
        run: |
          echo "$(python --version)"
          echo "$(python3 --version)"

      - name: Cache dependencies
        uses: actions/cache@v2
        id: pip-cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-pip-

      - name: Install pip
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
