name: Setup static library

on: workflow_call
  inputs:
    python-version:
      required: true
      type: string
    library:
      required: true
      type: string

jobs:
  library-setup:
    name: Setup external static check library
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ${{ inputs.library }}
