name: Static Code Analysis
on: pull_request

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get changed files
      id: changed-python-files
      uses: tj-actions/changed-files@v14.6
      with:
        files: |
          !.**
          **/*.py
    - name: Set up Python ${{ matrix.python-version }}
      if: steps.changed-python-files.outputs.all_changed_and_modified_files != ''
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache dependencies
      if: steps.changed-python-files.outputs.all_changed_and_modified_files != ''
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-pip-

    - name: Install dependencies
      if: steps.changed-python-files.outputs.all_changed_and_modified_files != ''
      run: |
        python -m pip install --upgrade pip
        pip install pycln
    - name: Run pycln
      if: steps.changed-python-files.outputs.all_changed_and_modified_files != ''
      run: |
        pycln --check ${{ steps.changed-python-files.outputs.all_changed_and_modified_files }}
