on: pull_request
name: Run Security Scans

jobs:
  pip-setup:
    uses: ./.github/workflows/init-static-check-library.yml

  bandit:
    name: Bandit
    runs-on: ubuntu-latest
    needs: pip-setup

    steps:
      - name: Install bandit
        run: pip install bandit

      - name: Print Python version
        run: |
          echo "$(python --version)"
          echo "$(python3 --version)"

      - name: Python Static Security Scan
        id: python-static-security-scan
        run: |
          bandit *.py -lll || :
          rc=0
          banditoutput=$(bandit *.py -lll || rc=1) ; echo "$banditoutput" > python-bandit-results

      - name: Store Bandit artifact
        uses: actions/upload-artifact@v2
        with:
          name: bandit-log
          path: python-bandit-results

  safety:
    name: Safety
    runs-on: ubuntu-latest
    needs: pip-setup

    steps:
      - name: Install safety
        run: pip install safety==1.10.3

      - name: Print Python version
        run: |
          echo "$(python --version)"
          echo "$(python3 --version)"

      - name: Safety Check
        id: python-safety-check
        run: |
          safety check -r requirements.txt || :
          rc=0
          safetyoutput=$(safety check -r requirements.txt || :) ; echo "$safetyoutput" > python-safety-results

      - name: Store Safety artifact
        uses: actions/upload-artifact@v2
        with:
          name: safety-log
          path: python-safety-results

