name: Version Bump

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic Version Number, e.g. MAJOR.MINOR.PATCH"
        required: true
        type: text

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          echo "Version: v$VERSION"
        env:
          VERSION: ${{ github.event.inputs.version }}

      - name: Create commits
        run: |
          git config user.name "Brad Luczywo"
          git config user.email "BradLucky@users.noreply.github.com"
          git switch -c version-bump-${{ github.event.inputs.version }}
          echo "${{ github.event.inputs.version }}" >> version.json
          git commit -am "Version bump ${{ github.event.inputs.version }}"
          git push -u origin HEAD

      - name: Create Pull Request
        run: |
          prRef="$(gh pr create --fill)"
          echo "PR_REF="$prRef >> $GITHUB_ENV 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo Pull Request
        run: |
          echo "PR: ${{ env.PR_REF }}"

      - name: Merge Pull Request
        run: |
          gh pr merge ${{ env.PR_REF }} --merge --delete-branch --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
