name: Version Bump

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic Version Number, e.g. MAJOR.MINOR.PATCH"
        required: true
        type: text

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - run: |
          echo "Version: v$VERSION"
        env:
          VERSION: ${{ github.event.inputs.version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: |
            version.json
          commit-message: 'Version bump'
          branch: version-bump-${{ github.event.inputs.version }}
          delete-branch: true
          title: 'Version Bump ${{ github.event.inputs.version }}'
