name: Version Bump

#       version:
#         description: "Semantic Version Number, e.g. MAJOR.MINOR.PATCH"
#         required: true
#

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic Version Number, e.g. MAJOR.MINOR.PATCH"
        required: true
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Version: $VERSION"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          VERSION: ${{ github.event.inputs.version }}
          TAGS: ${{ github.event.inputs.tags }}
