name: Version Bump

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic Version Number, e.g. MAJOR.MINOR.PATCH"
        required: true
        type: text

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/hotfix/v') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          echo "Version: v${{ github.event.inputs.version }}"

      - name: Create commits
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git pull
          git switch -c version-bump-${{ github.event.inputs.version }}
          jq '.version = "${{ github.event.inputs.version }}"' version.json > tmp.json && mv tmp.json version.json
          git add version.json
          git commit -m "Version bump ${{ github.event.inputs.version }}"
          git push -u origin HEAD

      - name: Create Pull Request
        run: |
          prRef="$(gh pr create --fill)"
          echo "PR_REF="$prRef >> $GITHUB_ENV 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        run: |
          gh pr merge ${{ env.PR_REF }} --merge --delete-branch --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
