name: Version Bump

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic Version Number, e.g. MAJOR.MINOR.PATCH"
        required: true
        type: text

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - run: |
          echo "Version: v$VERSION"
        env:
          VERSION: ${{ github.event.inputs.version }}
